### ISSUE TITLE
2017/03/24 一个新问题

### ISSUE THREAD

**Issue by TokyoAndroid** [TonnyL/PaperPlane#10]
SearchFragment中的onOptionsItemSelected方法里的返回键图标不起作用，应该写在SearchActivity里面。

**Comment by TonnyL** [comment]
恩，感谢，之前也有人提到过。后面重构的改。

**Comment by TonnyL** [comment]
@TokyoAndroid 
I am sorry to say that the search function was removed from version v3.3.0. If the amount of people who have strong mind to this function after the app was updated at google play is big enough, I will add it back.

If there is no other question, I will close this issue.
