### ISSUE TITLE
关于Shortcuts的问题

### ISSUE THREAD

**Issue by woofww** [TonnyL/PaperPlane#11]
您好，我注意到您的这款应用是支持Android Shortcuts那个功能的，在Nova Launcher下工作完全正常。然后我在开发过程中也想加入这个功能，但是按照官方文档做的时候，在Nova Launcher上一直无法实现该功能，想请教您一下这个功能在实现过程中还有需要值得注意的么？

**Comment by TonnyL** [comment]
你好，这个坑我也遇到过，在官方的pixel launcher上表现正常，但是到了Nova launcher上，有的shortcut就不能正常显示了。后来我发现貌似是因为intent 和 categories等需要配置完全。可以参考这个：

```xml
 <intent
            android:action="com.marktony.zhihudaily.homepage"
            android:targetPackage="com.marktony.zhihudaily"
            android:targetClass="com.marktony.zhihudaily.homepage.MainActivity" />

        <categories android:name="android.shortcut.conversation" />
```

可以参考我的文章： [老司机带你吃牛轧糖--适配Android 7.1 Nougat新特性](http://www.jianshu.com/p/f56f2e709ad8)

希望对你有所帮助，如果有任何问题，请不要犹豫，直接在issue里面说明，我们一起解决。

@woofww

**Comment by woofww** [comment]
不知道是什么原因，写Shortcut测试Demo的时候显示完全没问题，但是用同样的方法集成到项目中就是说啥也显示不出来，手头还没有7.0的机器，真是不知道怎么回事了

**Comment by TonnyL** [comment]
Manifest注册了吗？

可以的话可以给我发个Apk，我现在手头有7.1的设备

**Comment by woofww** [comment]
感谢感谢，也找朋友借了一台设备，虽然7.0设备上 Shortcut 可以显示，但是又开始报 App isn't installed 应该可能这个问题。我再去 Google 研究研究

**Comment by woofww** [comment]
7.0及以上工作没问题了，就是这Nova一直不成，真是诡异

**Comment by TonnyL** [comment]
貌似nova和pixel launcher解析的方式不同😂

**Comment by woofww** [comment]
好吧，我最近再研究研究，也非常感谢哈，以后有问题还会多多交流

**Comment by TonnyL** [comment]
ok，请问还有别的问题吗？没有的话我就把这个issue关掉 了。

**Comment by woofww** [comment]
没有了，请关闭吧

**Comment by TonnyL** [comment]
ok，有什么问题的话，不要犹豫，开一个issue，我们一起讨论。😉
