### ISSUE TITLE
App运行崩溃问题

### ISSUE THREAD

**Issue by ScWen7** [TonnyL/PaperPlane#12]
机型：华为荣耀6 H60-L02  
Android 版本：4.4
崩溃位置：收藏界面点击Toolbar 进入搜索界面之后，在搜索框连续输入多次文本App崩溃

**Comment by TonnyL** [comment]
OK，已记录

**Comment by TonnyL** [comment]
@ScWen7 
I am sorry to say that the search function was removed from version v3.3.0. If a lot people had strong mind to this, I will add it back if possible.

If there is no other question, I will close this issue.
