### ISSUE TITLE
如果第一次进入应用，且没网，会奔溃

### ISSUE THREAD

**Issue by 374901588** [TonnyL/PaperPlane#13]
原因出在DoubanMomentFragment第一次进入时因为没网DoubanMomentFragment会弹出一个SnackBar，（该SnackBar是相对于RefreshLayout显示的），但是在fragment_liset布局中缺少父布局CoordinatorLayout，而SnackBar所依赖的view又要在以CoordinatorLayout作为直接父布局，所以会奔溃。

**Comment by TonnyL** [comment]
感谢，已记录。

**Comment by TonnyL** [comment]
@374901588 
Fixed at version 3.3.0. If there is no other question, I will close this issue.
