### ISSUE TITLE
学习你的代码写了个APP

### ISSUE THREAD

**Issue by liliping101** [TonnyL/PaperPlane#14]
大神，您好，我参考你的源码也写一个几乎一样的APP，不过我里面采用了一些新的框架butterknife、retrofit、rxjava、greendao。 同时也优化了一些bug。
我想上传的我的git上， 但我想毕竟是算是抄袭你的，不知道上传的内容注意点什么，请指导。

**Comment by TonnyL** [comment]
@liliping101 你好

直接上传吧，不用考虑啥了。不过需要注意的是版权问题，不是代码的版权，而是内容的版权。如果是上传到应用商店的话，有可能会收到 知乎 的邮件的，因为我们的应用的确侵犯了内容提供商的版权。(我收到了知乎的邮件)所以，最好是只用于代码研究，学习。

另外，开源之后把地址给我吧，我给个star。嘿嘿😋。

**Comment by liliping101** [comment]
代码地址：https://github.com/liliping101/PaperPlane-study
大神多提宝贵意见。

**Comment by nbpzjy** [comment]
很赞

**Comment by TonnyL** [comment]
@liliping101 如果没有其他的问题的话，那我就把issue关掉了。还有其他问题的话，重开一个就好了，嘿嘿，加油啊！

**Comment by TonnyL** [comment]
Then I will close this issue. If you find any problems or good ideas, DO NOT hesitate to reopen it or just open another one. Happy coding 😃!
