### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by asmallkite** [TonnyL/PaperPlane#17]
当连续下滑页面（知乎日报，豆瓣一刻，果壳精选的任意一个），一直下滑，不久就会报出OOM.
个人觉得，作者的这种 二级详情页面 的缓存方式不太好，发送了那么多广播。

log附上
[log.txt](https://github.com/TonnyL/PaperPlane/files/1167225/log.txt)

**Comment by TonnyL** [comment]
是的。

如果你有更好的解决办法，欢迎讨论。

**Comment by TonnyL** [comment]
感觉可以通过intent service来实现😂

**Comment by TonnyL** [comment]
@asmallkite 如果没有其他问题的话，我要关掉这个issue了。
