### ISSUE TITLE
学习作者的代码写了个App

### ISSUE THREAD

**Issue by iMeiji** [TonnyL/PaperPlane#18]
很久之前我在看 `第一行代码` 的时候就在 V2 看到你的 知乎专栏 App, 当时觉得界面很赞, 就开始关注作者了, 然后学习作者的 知乎专栏 App , 把它改成 MVP 架构(当学习MVP). 接着看到作者的 纸飞机 App, 还有 7 天开发一个App并上架 的文章, 我就决定要自己写一款能上架的App了 , 当时看到 卡片新闻 停止更新了, 我就决定开发一款新闻类的App, 开发了有半年时间, 前几个月上架酷安, 到目前为止有 1W 的下载量, 觉得还行吧,就想过来跟作者分享下 , 哈哈 
项目地址 : https://github.com/iMeiji/Toutiao

随便问下作者的英文怎么学习的?感觉你的英文很6啊

**Comment by TonnyL** [comment]
Nice job! APP很棒。感谢你的关注，嘿嘿。不过可能需要注意的是版权问题，因为我之前就遇到过，所以才导致了纸飞机APP的停更。

其实我英语也不好😂，6级都还没过呢🤣

**Comment by iMeiji** [comment]
@TonnyL 哈哈, 版权的确是个问题, 学渣英文4级都没过...
作者大大给个 star 我呗(手动滑稽)

**Comment by TonnyL** [comment]
@iMeiji  多在简书，掘金上写文章，star就会渐渐多起来的😆

**Comment by TonnyL** [comment]
@iMeiji  如果没有其他的问题的话，我要关掉这个issue了😀

**Comment by iMeiji** [comment]
@TonnyL 刚刚收到头条发来的侵权邮件了, 我把App都下架了 , 唉

**Comment by TonnyL** [comment]
@iMeiji 很正常啊，今日头条这种公司。再说咱们侵权在先。玩点别的吧，国内环境这么差。可以玩玩像slack, dribbble, Instagram这种，api都挺好，而且规范国内的我只推荐teambition和豆瓣，但是豆瓣次数限制。可以看看的我Awesome_APIs那个repo

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by iMeiji** [comment]
@TonnyL 好的, 用 API 学习还是可以的, 自己研究也足够了, 上架这种东西经历过就不错了, 哈哈, 谢谢你了
