### ISSUE TITLE
PaperPlane app for WordPress Blog

### ISSUE THREAD

**Issue by sobujbd** [TonnyL/PaperPlane#19]
**PaperPlane** app looks very nice. :cupid:
Can you design a app for **WordPress** blog site with **JSON API** like **PaperPlane** app?

**Comment by TonnyL** [comment]
Thanks for you praise. The app was developed when I was in sophomore, but I am in senior and working now. The lack of time makes me feel developing such an app is beyond my reach. Sorry for that.
