### ISSUE TITLE
导入之后 字体文件报错怎么回事儿？

### ISSUE THREAD

**Issue by yuanchenghao** [TonnyL/PaperPlane#22]
C:\Users\Administrator\Desktop\PaperPlane-master\PaperPlane-master\app\src\main\res\font\product_sans_italic.ttfError:Error: The file name must end with .xml

**Comment by TonnyL** [comment]
Request android studio 3.0 and late.

**Comment by yuanchenghao** [comment]
最新的不是2.3.3么？

**Comment by TonnyL** [comment]
See https://developer.android.com/studio/preview/index.html and https://androidstudio.googleblog.com/2017/09/android-studio-30-beta-6-is-now.html. 🌝

**Comment by yuanchenghao** [comment]
哦好的 谢谢了

**Comment by TonnyL** [comment]
Any question yet? Or I will close this issue.🙈

**Comment by yuanchenghao** [comment]
嗯 如果不升级最近版本 有什么办法全局改变字体

**Comment by TonnyL** [comment]
See here: https://www.zhihu.com/question/38615247/answer/179928113

**Comment by yuanchenghao** [comment]
close this issue,thank you!

**Comment by TonnyL** [comment]
If you have any other problems, do not hesitate to open another one or just reopen it.😊 Happy coding!
