### ISSUE TITLE
folder name interfaze should change to interface?

### ISSUE THREAD

**Issue by linking123** [TonnyL/PaperPlane#23]
as title said

**Comment by TonnyL** [comment]
Hi, @linking123 

Good question!  `interface` is reserved word of Java, so the package name can not be `interface` and if you are going to modify `interfaze` to `interface`, it won't be success.  The pronunciation of `interfaze` is much similar to `interface`'s, aha? 😉

**Comment by TonnyL** [comment]
Hi, @linking123 

If there is no other problems, I will close this issue.
