### ISSUE TITLE
关于CollapsingToolbarLayout的toolbar

### ISSUE THREAD

**Issue by liliping101** [TonnyL/PaperPlane#24]
您好：
     我想请教你一个问题，就是你现在APP里面detail窗口里的CollapsingToolbarLayout下的toolbar上滑时会滑出整个界面。但是我按照android教程里写都不会滑出去。而且app:layout_collapseMode="pin"也设置，按照API的说法，设置为pin：CollapsingToolbarLayout折叠后，此布局将固定在顶部。

**Comment by TonnyL** [comment]
还需要将 `app:layout_scrollFlags="scroll|enterAlwaysCollapsed|enterAlways"` 设置给 `CollapsingToolbarLayout `. 具体的可以参照: https://github.com/TonnyL/PaperPlane/blob/master/app/src/main/res/layout/fragment_details.xml#L39

**Comment by liliping101** [comment]
谢谢你的指教，问题已解决
