### ISSUE TITLE
ProductSans possible copyright infringement

### ISSUE THREAD

**Issue by jahirfiquitiva** [TonnyL/PaperPlane#25]
Hello

I just came across your project and it looks quite good. Great work.

Anyways, I noticed you are using Google's ProductSans font, which is not open-source, so I thought I should let you know so you don't run into possible copyright infringements.

Check [license site](https://fonts.google.com/license/productsans)

**Comment by TonnyL** [comment]
Hi, @jahirfiquitiva 

Thanks for your notice. Yes I know that Product Sans is not suitable for my personal use, and this project is just for development(This app is NOT available on Google Play or any other app stores), but anyway, if it is necessary I will remove this font.

Thanks again 😉.

**Comment by jahirfiquitiva** [comment]
I don't know if it's necessary, but you might probably find a suitable similar font that you can use, just to prevent any infringements. 😀

**Comment by TonnyL** [comment]
Hah hah, I will replace with another open-source font.

**Comment by TonnyL** [comment]
I've replaced product sans with roboto. Thanks for pointing out my fault 😉. And I will close this issue now, if you get any other issue, do not hesitate to reopen it or just file another one.
