### ISSUE TITLE
2017/03/23果壳精选的API更改了一下，导致果壳精选获取不到数据了。

### ISSUE THREAD

**Issue by TokyoAndroid** [TonnyL/PaperPlane#9]
把GuokrHandpickNews内的内部类source_data中的id从int变为String就能解决问题了，望更新哦~
你的代码写的很棒，受益匪浅，感谢！

**Comment by TonnyL** [comment]
好的，我会在下次重构的时候更换的。谢谢你的好评，其实代码还有很多不足的地方啦，嘿嘿。感谢你指出问题哟😀

**Comment by TonnyL** [comment]
@TokyoAndroid 
 Hi, 
The API of guokr handpick was changed into another one.  You can check the [RetrofitService.java](https://github.com/TonnyL/PaperPlane/blob/master/app/src/main/java/com/marktony/zhihudaily/retrofit/RetrofitService.java) for more details.

If there is no other question, I will close this issue.
